---
- hosts: localhost
  connection: local

  # vars:
  # aws_region: "ap-south-1"


  tasks:
  - name: start an instance with a public IP address
    amazon.aws.ec2_instance:
      name: "{{ item.name }}"
      key_name: "ansible-master-key"
      instance_type: t2.micro
      security_group: default
      region: ap-south-1
      aws_access_key: "{{ec2_access_key}}"  # From vault as defined
      aws_secret_key: "{{ec2_secret_key}}"  # From vault as defined      
      network:
        assign_public_ip: true
      image_id: "{{ item.image }}"
      tags:
        Environment: project

    loop: 
    - { image: "ami-00bb6a80f01f03502", name: "manage-node-1" }
    - { image: "ami-03c68e52484d7488f", name: "manage-node-2" }
    - { image: "ami-0d682f26195e9ec0f", name: "manage-node-3" }

      